version: '3.8'
volumes:
  pg_data:
  static:
  media:

services:
  
  db:
    image: postgres:13.10-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    build: ../backend/
    # image: mrshifty/foodgram_backend
    volumes:
      - static:/static/
      - media:/media/
    depends_on:
      - db
    env_file:
      - .env
    # entrypoint: /usr/bin/entrypoint.sh
    restart: always
    container_name: foodgram_backend
  
  frontend:
    image: mrshifty/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db
    container_name: foodgram_frontend
  
  nginx:
    image: nginx:1.19.3
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/var/html/static/
      - media:/var/html/media/
    depends_on:
      - backend
    container_name: foodgram_nginx
