version: '3.8'
volumes:
  pg_data:
  static:
  media:

services:
  
  db:
    image: postgres:13.10
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    build: ../backend/
    volumes:
      - static:/foodgram_backend_static/
      - media:/app/media/
    depends_on:
      - db
    env_file:
      - .env
    # entrypoint: /usr/bin/entrypoint.sh
    restart: always
    container_name: foodgram_backend
  
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
  
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
    container_name: foodgram_nginx
