# Generated by Django 3.2 on 2023-07-10 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_Create_related_name_for_recipeingredient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorites',
            options={'default_related_name': 'favorites', 'verbose_name': 'избранный рецепт', 'verbose_name_plural': 'избранные рецепты'},
        ),
        migrations.AlterField(
            model_name='favorites',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
