# Generated by Django 3.2 on 2023-07-12 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_Fixed_related_name_and_field_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
