# Generated by Django 3.2 on 2023-07-16 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_Update_shopping_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientstorecipe', to='recipes.recipe', verbose_name='рецепт'),
        ),
    ]
