# Generated by Django 3.2 on 2023-07-17 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_Update_field_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'default_related_name': 'shopping_cart', 'verbose_name': 'Список покупок', 'verbose_name_plural': 'Списки покупок'},
        ),
    ]
