# Generated by Django 3.2 on 2023-07-17 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_Update_verbose_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'default_related_name': 'shopping_cart', 'verbose_name': 'cписок покупок', 'verbose_name_plural': 'cписки покупок'},
        ),
    ]
