# Generated by Django 3.2 on 2023-07-05 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_Create_follow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Подписки', 'verbose_name_plural': 'Подписки'},
        ),
    ]
