# Generated by Django 3.2 on 2023-07-05 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_Edited_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'подписки', 'verbose_name_plural': 'подписки'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',), 'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
    ]
